### ISSUE TITLE
Suggestion to maintain aspect ratio of images

### ISSUE THREAD

**Issue by stemount** [EugeneGohh/Personal-Portfolio-Website#2]
stolen from @eddiejaoude discord:

https://discord.com/channels/699608417039286293/699609465867075594/777119954414862339

![image](https://user-images.githubusercontent.com/150512/99146854-d1547600-2673-11eb-87ce-77bdc2b05a7d.png)

**Comment by EugeneGohh** [comment]
Thank you for contributing to this. I learned.

**Comment by eddiejaoude** [comment]
Awesome 💪
